#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 29 20:56:15 2020

@author: tanvir
"""
from ase.build import fcc111, add_adsorbate, molecule
from ase.io import write
from ase.io.vasp import write_vasp

# create a slab of the atom mentioned in '..'. Note, size (3,3,6) means 3 times 3 grid with 6 layers of atoms
slab = fcc111('Cu', size=(3,3,6))
# creating the adsorbate
benzene = molecule('C6H6')

# adding the adsorbate to the slab at position (x=5,y=5) at a height of z=5
add_adsorbate(slab, benzene, 5, position=(5,5))

# centering the slab after adding the adsorbate and adding vacuum at the top and bottom of the structure
slab.center(vacuum=10.0, axis=2)
m = slab.get_positions() # I just added to check the positions (x, y, z)

write('slab.xyz', slab) # will write the coordinate into a xyz file
write_vasp('POSCAR', slab) # will write the coordinate into a POSCAR file
# If you are curious to know how the super cell will look like in POSCAR, use the following 3 lines
'''a = read('slab.xyz')
cell = a.get_cell()
print(cell.round(3))'''
